pandoc 1_OS_Obrady-plenarne.odt -t html >> 1_OS_Obrady-plenarne.html
pandoc 2_OS_Gosp-polit-spol1.odt -t html >> 2_OS_Gosp-polit-spol1.html
pandoc 3_OS_Gosp-polit-spol2.odt -t html >> 3_OS_Gosp-polit-spol2.html
pandoc 4_OS_Gosp-polit-spol3.odt -t html >> 4_OS_Gosp-polit-spol3.html
pandoc 5_OS_Gosp-polit-spol4.odt -t html >> 5_OS_Gosp-polit-spol4.html
pandoc 6_OS_Gosp-polit-spol5.odt -t html >> 6_OS_Gosp-polit-spol5.html
pandoc 7_OS_Gosp-polit-spol6.odt -t html >> 7_OS_Gosp-polit-spol6.html
pandoc 8_OS_Gosp-polit-spol7.odt -t html >> 8_OS_Gosp-polit-spol7.html
pandoc 9_OS_Gosp-polit-spol8.odt -t html >> 9_OS_Gosp-polit-spol8.html
pandoc 10_OS_Gosp-polit-spol9.odt -t html >> 10_OS_Gosp-polit-spol9.html
pandoc 11_OS_Gosp-polit-spol10.odt -t html >> 11_OS_Gosp-polit-spol10.html
pandoc 12_OS_Pluralizmu1.odt -t html >> 12_OS_Pluralizmu1.html
pandoc 13_OS_Pluralizmu2.odt -t html >> 13_OS_Pluralizmu2.html
pandoc 14_OS_Pluralizmu3.odt -t html >> 14_OS_Pluralizmu3.html
pandoc 15_OS_Pluralizmu4.odt -t html >> 15_OS_Pluralizmu4.html
pandoc 16_OS_Pluralizmu5.odt -t html >> 16_OS_Pluralizmu5.html
pandoc 17_OS_Pluralizmu6.odt -t html >> 17_OS_Pluralizmu6.html
pandoc 18_OS_Pluralizmu7.odt -t html >> 18_OS_Pluralizmu7.html
pandoc 19_OS_Pluralizmu8.odt -t html >> 19_OS_Pluralizmu8.html
pandoc 20_OS_Pluralizmu9.odt -t html >> 20_OS_Pluralizmu9.html
pandoc 21_OS_Pluralizmu10.odt -t html >> 21_OS_Pluralizmu10.html
pandoc 22_OS_ReformPolit1.odt -t html >> 22_OS_ReformPolit1.html
pandoc 23_OS_ReformPolit2.odt -t html >> 23_OS_ReformPolit2.html
pandoc 24_OS_ReformPolit3.odt -t html >> 24_OS_ReformPolit3.html
pandoc 25_OS_ReformPolit4.odt -t html >> 25_OS_ReformPolit4.html
pandoc 26_OS_ReformPolit5.odt -t html >> 26_OS_ReformPolit5.html
pandoc 27_OS_ReformPolit6.odt -t html >> 27_OS_ReformPolit6.html
pandoc 28_OS_ReformPolit7.odt -t html >> 28_OS_ReformPolit7.html
pandoc 29_OS_ReformPolit8.odt -t html >> 29_OS_ReformPolit8.html
pandoc 30_OS_ReformPolit9.odt -t html >> 30_OS_ReformPolit9.html
pandoc 31_OS_Ekologii1.odt -t html >> 31_OS_Ekologii1.html
pandoc 32_OS_Ekologii2.odt -t html >> 32_OS_Ekologii2.html
pandoc 33_OS_Ekologii3.odt -t html >> 33_OS_Ekologii3.html
pandoc 34_OS_Ekologii4.odt -t html >> 34_OS_Ekologii4.html
pandoc 35_OS_Ekologii5.odt -t html >> 35_OS_Ekologii5.html
pandoc 36_OS_Ekologii6.odt -t html >> 36_OS_Ekologii6.html
pandoc 37_OS_Ekologii7.odt -t html >> 37_OS_Ekologii7.html
pandoc 38_OS_Ekologii8.odt -t html >> 38_OS_Ekologii8.html
pandoc 39_OS_Gornictwa1.odt -t html >> 39_OS_Gornictwa1.html
pandoc 40_OS_Gornictwa2.odt -t html >> 40_OS_Gornictwa2.html
pandoc 41_OS_Gornictwa3.odt -t html >> 41_OS_Gornictwa3.html
pandoc 42_OS_Gornictwa4.odt -t html >> 42_OS_Gornictwa4.html
pandoc 43_OS_Gornictwa5.odt -t html >> 43_OS_Gornictwa5.html
pandoc 44_OS_Gornictwa6.odt -t html >> 44_OS_Gornictwa6.html
pandoc 45_OS_Gornictwa7.odt -t html >> 45_OS_Gornictwa7.html
pandoc 46_OS_Gornictwa8.odt -t html >> 46_OS_Gornictwa8.html
