pandoc 1_OS_Obrady-plenarne.odt -t html >> htmls/1_OS_Obrady-plenarne.html
pandoc 2_OS_Gosp-polit-spol1.odt -t html >> htmls/2_OS_Gosp-polit-spol1.html
pandoc 3_OS_Gosp-polit-spol2.odt -t html >> htmls/3_OS_Gosp-polit-spol2.html
pandoc 4_OS_Gosp-polit-spol3.odt -t html >> htmls/4_OS_Gosp-polit-spol3.html
pandoc 5_OS_Gosp-polit-spol4.odt -t html >> htmls/5_OS_Gosp-polit-spol4.html
pandoc 6_OS_Gosp-polit-spol5.odt -t html >> htmls/6_OS_Gosp-polit-spol5.html
pandoc 7_OS_Gosp-polit-spol6.odt -t html >> htmls/7_OS_Gosp-polit-spol6.html
pandoc 8_OS_Gosp-polit-spol7.odt -t html >> htmls/8_OS_Gosp-polit-spol7.html
pandoc 9_OS_Gosp-polit-spol8.odt -t html >> htmls/9_OS_Gosp-polit-spol8.html
pandoc 10_OS_Gosp-polit-spol9.odt -t html >> htmls/10_OS_Gosp-polit-spol9.html
pandoc 11_OS_Gosp-polit-spol10.odt -t html >> htmls/11_OS_Gosp-polit-spol10.html
pandoc 12_OS_Pluralizmu1.odt -t html >> htmls/12_OS_Pluralizmu1.html
pandoc 13_OS_Pluralizmu2.odt -t html >> htmls/13_OS_Pluralizmu2.html
pandoc 14_OS_Pluralizmu3.odt -t html >> htmls/14_OS_Pluralizmu3.html
pandoc 15_OS_Pluralizmu4.odt -t html >> htmls/15_OS_Pluralizmu4.html
pandoc 16_OS_Pluralizmu5.odt -t html >> htmls/16_OS_Pluralizmu5.html
pandoc 17_OS_Pluralizmu6.odt -t html >> htmls/17_OS_Pluralizmu6.html
pandoc 18_OS_Pluralizmu7.odt -t html >> htmls/18_OS_Pluralizmu7.html
pandoc 19_OS_Pluralizmu8.odt -t html >> htmls/19_OS_Pluralizmu8.html
pandoc 20_OS_Pluralizmu9.odt -t html >> htmls/20_OS_Pluralizmu9.html
pandoc 21_OS_Pluralizmu10.odt -t html >> htmls/21_OS_Pluralizmu10.html
pandoc 22_OS_ReformPolit1.odt -t html >> htmls/22_OS_ReformPolit1.html
pandoc 23_OS_ReformPolit2.odt -t html >> htmls/23_OS_ReformPolit2.html
pandoc 24_OS_ReformPolit3.odt -t html >> htmls/24_OS_ReformPolit3.html
pandoc 25_OS_ReformPolit4.odt -t html >> htmls/25_OS_ReformPolit4.html
pandoc 26_OS_ReformPolit5.odt -t html >> htmls/26_OS_ReformPolit5.html
pandoc 27_OS_ReformPolit6.odt -t html >> htmls/27_OS_ReformPolit6.html
pandoc 28_OS_ReformPolit7.odt -t html >> htmls/28_OS_ReformPolit7.html
pandoc 29_OS_ReformPolit8.odt -t html >> htmls/29_OS_ReformPolit8.html
pandoc 30_OS_ReformPolit9.odt -t html >> htmls/30_OS_ReformPolit9.html
pandoc 31_OS_Ekologii1.odt -t html >> htmls/31_OS_Ekologii1.html
pandoc 32_OS_Ekologii2.odt -t html >> htmls/32_OS_Ekologii2.html
pandoc 33_OS_Ekologii3.odt -t html >> htmls/33_OS_Ekologii3.html
pandoc 34_OS_Ekologii4.odt -t html >> htmls/34_OS_Ekologii4.html
pandoc 35_OS_Ekologii5.odt -t html >> htmls/35_OS_Ekologii5.html
pandoc 36_OS_Ekologii6.odt -t html >> htmls/36_OS_Ekologii6.html
pandoc 37_OS_Ekologii7.odt -t html >> htmls/37_OS_Ekologii7.html
pandoc 38_OS_Ekologii8.odt -t html >> htmls/38_OS_Ekologii8.html
pandoc 39_OS_Gornictwa1.odt -t html >> htmls/39_OS_Gornictwa1.html
pandoc 40_OS_Gornictwa2.odt -t html >> htmls/40_OS_Gornictwa2.html
pandoc 41_OS_Gornictwa3.odt -t html >> htmls/41_OS_Gornictwa3.html
pandoc 42_OS_Gornictwa4.odt -t html >> htmls/42_OS_Gornictwa4.html
pandoc 43_OS_Gornictwa5.odt -t html >> htmls/43_OS_Gornictwa5.html
pandoc 44_OS_Gornictwa6.odt -t html >> htmls/44_OS_Gornictwa6.html
pandoc 45_OS_Gornictwa7.odt -t html >> htmls/45_OS_Gornictwa7.html
pandoc 46_OS_Gornictwa8.odt -t html >> htmls/46_OS_Gornictwa8.html
pandoc 47_OS_Gornictwa9.odt -t html >> htmls/47_OS_Gornictwa9.html
pandoc 48_OS_Mlodziezy1.odt -t html >> htmls/48_OS_Mlodziezy1.html
pandoc 49_OS_Mlodziezy2.odt -t html >> htmls/49_OS_Mlodziezy2.html
pandoc 50_OS_Mlodziezy3.odt -t html >> htmls/50_OS_Mlodziezy3.html
pandoc 51_OS_Mlodziezy4.odt -t html >> htmls/51_OS_Mlodziezy4.html
pandoc 52_OS_Mlodziezy5.odt -t html >> htmls/52_OS_Mlodziezy5.html
pandoc 53_OS_Nauki1.odt -t html >> htmls/53_OS_Nauki1.html
pandoc 54_OS_Nauki2.odt -t html >> htmls/54_OS_Nauki2.html
pandoc 55_OS_Nauki3.odt -t html >> htmls/55_OS_Nauki3.html
pandoc 56_OS_Nauki4.odt -t html >> htmls/56_OS_Nauki4.html
pandoc 57_OS_PolMieszkaniowej1.odt -t html >> htmls/57_OS_PolMieszkaniowej1.html
pandoc 58_OS_PolMieszkaniowej2.odt -t html >> htmls/58_OS_PolMieszkaniowej2.html
pandoc 59_OS_PolMieszkaniowej3.odt -t html >> htmls/59_OS_PolMieszkaniowej3.html
pandoc 60_OS_PolMieszkaniowej4.odt -t html >> htmls/60_OS_PolMieszkaniowej4.html
pandoc 61_OS_ReformyPrawaSad1.odt -t html >> htmls/61_OS_ReformyPrawaSad1.html
pandoc 62_OS_ReformyPrawaSad2.odt -t html >> htmls/62_OS_ReformyPrawaSad2.html
pandoc 63_OS_ReformyPrawaSad3.odt -t html >> htmls/63_OS_ReformyPrawaSad3.html
pandoc 64_OS_ReformyPrawaSad4.odt -t html >> htmls/64_OS_ReformyPrawaSad4.html
pandoc 65_OS_ReformyPrawaSad5.odt -t html >> htmls/65_OS_ReformyPrawaSad5.html
pandoc 66_OS_ReformyPrawaSad6.odt -t html >> htmls/66_OS_ReformyPrawaSad6.html
pandoc 67_OS_ReformyPrawaSad7.odt -t html >> htmls/67_OS_ReformyPrawaSad7.html
pandoc 68_OS_ReformyPrawaSad8.odt -t html >> htmls/68_OS_ReformyPrawaSad8.html
pandoc 69_OS_ReformyPrawaSad9.odt -t html >> htmls/69_OS_ReformyPrawaSad9.html
pandoc 70_OS_Rolnictwa1.odt -t html >> htmls/70_OS_Rolnictwa1.html
pandoc 71_OS_Rolnictwa2.odt -t html >> htmls/71_OS_Rolnictwa2.html
pandoc 72_OS_Rolnictwa3.odt -t html >> htmls/72_OS_Rolnictwa3.html
pandoc 73_OS_Rolnictwa4.odt -t html >> htmls/73_OS_Rolnictwa4.html
pandoc 74_OS_Rolnictwa5.odt -t html >> htmls/74_OS_Rolnictwa5.html
pandoc 75_OS_Stowarzyszen1.odt -t html >> htmls/75_OS_Stowarzyszen1.html
pandoc 76_OS_Stowarzyszen2.odt -t html >> htmls/76_OS_Stowarzyszen2.html
pandoc 77_OS_Stowarzyszen3.odt -t html >> htmls/77_OS_Stowarzyszen3.html
pandoc 78_OS_Stowarzyszen4.odt -t html >> htmls/78_OS_Stowarzyszen4.html
pandoc 79_OS_Stowarzyszen5.odt -t html >> htmls/79_OS_Stowarzyszen5.html
pandoc 80_OS_Stowarzyszen6.odt -t html >> htmls/80_OS_Stowarzyszen6.html
pandoc 81_OS_Stowarzyszen7.odt -t html >> htmls/81_OS_Stowarzyszen7.html
pandoc 82_OS_SrodkowPrzekaz1.odt -t html >> htmls/82_OS_SrodkowPrzekaz1.html
pandoc 83_OS_SrodkowPrzekaz2.odt -t html >> htmls/83_OS_SrodkowPrzekaz2.html
pandoc 84_OS_SrodkowPrzekaz3.odt -t html >> htmls/84_OS_SrodkowPrzekaz3.html
pandoc 85_OS_SrodkowPrzekaz4.odt -t html >> htmls/85_OS_SrodkowPrzekaz4.html
pandoc 86_OS_SrodkowPrzekaz5.odt -t html >> htmls/86_OS_SrodkowPrzekaz5.html
pandoc 87_OS_SrodkowPrzekaz6.odt -t html >> htmls/87_OS_SrodkowPrzekaz6.html
pandoc 88_OS_Zdrowia1.odt -t html >> htmls/88_OS_Zdrowia1.html
pandoc 89_OS_Zdrowia2.odt -t html >> htmls/89_OS_Zdrowia2.html
pandoc 90_OS_Zdrowia3.odt -t html >> htmls/90_OS_Zdrowia3.html
pandoc 91_OS_Zdrowia4.odt -t html >> htmls/91_OS_Zdrowia4.html
pandoc 92_OS_Zdrowia5.odt -t html >> htmls/92_OS_Zdrowia5.html
pandoc 93_OS_IndeksacjiPlac1.odt -t html >> htmls/93_OS_IndeksacjiPlac1.html
pandoc 94_OS_Gosp-polit-spol11.odt -t html >> htmls/94_OS_Gosp-polit-spol11.html
pandoc 95_OS_Gosp-polit-spol12.odt -t html >> htmls/95_OS_Gosp-polit-spol12.html
pandoc 96_OS_Gosp-polit-spol13.odt -t html >> htmls/96_OS_Gosp-polit-spol13.html
